name: Cerrebrus CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Server Dependencies
        run: cd server && npm ci

      - name: Install Client Dependencies
        run: cd client && npm ci

      # - name: Run Server Tests
      #   run: cd server && npm test

      # - name: Run Client Tests
      #   run: cd client && npm test

      - name: Build Client
        run: cd client && npm run build
